name: test build deploy

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build_sdist:
    name: Build sdist on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install build
        run: python -m pip install build --user
      - name: Build the source tarball
        run: python -m build --sdist .
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: ./dist

  build_wheels:
    name: Build wheels on ${{ matrix.os }} - ${{ matrix.arch }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        arch: ['x86_64']
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macOS-latest'
        include:
          - os: 'ubuntu-latest'
            arch: 'aarch64'
          - os: 'macOS-latest'
            arch: 'arm64'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if: ${{ runner.os == 'Linux' && matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          SEABREEZE_DISABLE_FH4: "yes"

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  deploy_pypi:
    name: deploy to pypi
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: false
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: ./dist
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./dist
      # push all tagged versions to pypi.org
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
